## Gradle

org.gradle.jvmargs = -Xmx1G
org.gradle.daemon = true
org.gradle.parallel = true
org.gradle.caching = true
#org.gradle.configuration-cache = true
org.gradle.unsafe.configuration-cache-problems = warn

## Dependents

parchment_minecraft_version = 1.21.1
parchment_mappings_version = 2024.11.13
minecraft_version = 1.21.1
minecraft_version_range = [1.21.1, 1.22)
neo_version = 21.1.152
neo_version_range = [21.1.152,)
loader_version_range = [4,)

create_version = 6.0.6-98
ponder_version = 1.0.59
flywheel_version = 1.0.4
registrate_version = MC1.21-1.3.0+62
catnip_version = 0.8.54

jei_version = 19.22.0.315
curios_version = 9.2.2
jade_id = 6011258 

## Mod Properties

mod_id = petrolpark
mod_name = Petrolpark's Library
mod_license = All Rights Reserved
mod_version = 1.4.18
mod_group_id = com.petrolpark
mod_authors = Petrolpark
mod_description = Common code for petrolpark's Create add-ons and other Minecraft mods
